counter: 0

reset:
  inventory: true
  experience: true
  enderchest: false
  advancements: false
  statistics: false

world-settings:
  overworld:
    seed: 0 # 0 for random
    generate-structures: true
    bonus-chest: false

    type: "NORMAL" # NORMAL, FLAT, LARGE_BIOMES, AMPLIFIED
    generatorSettings: ""

    generator: ""
    biome-provider: ""

  nether:
    seed: 0 # 0 for random
    generate-structures: true
    bonus-chest: false

    type: "NORMAL" # NORMAL, FLAT, LARGE_BIOMES, AMPLIFIED
    generatorSettings: ""

    generator: ""
    biome-provider: ""

  the_end:
    seed: 0 # 0 for random
    generate-structures: true
    bonus-chest: false

    type: "NORMAL" # NORMAL, FLAT, LARGE_BIOMES, AMPLIFIED
    generatorSettings: ""

    generator: ""
    biome-provider: ""
